"""
Install BillionMail on the Hostinger VPS.

Idempotent steps:
1. Clone or update repo at /opt/billionmail
2. Generate strong .env with custom HTTP/HTTPS ports (8088/8443) to avoid conflicting
   with Traefik (Easypanel) on 80/443.
3. Pull images and `docker compose up -d`
4. Wait for containers to be healthy and report status

Run AFTER you've reviewed scripts/billionmail/check_vps.py output.
This script does NOT touch DNS or Traefik. UFW is NOT enabled automatically (to avoid
SSH lockout). Activate UFW separately once you've verified ports.
"""
import secrets
import string
import sys
import time
import os

sys.path.insert(0, os.path.dirname(__file__))
from _ssh import connect, run, write_remote_file  # type: ignore

REPO_DIR = '/opt/billionmail'
REPO_URL = 'https://github.com/aaPanel/BillionMail.git'

# Custom ports so BillionMail's `core` container does not collide with Traefik on 80/443.
HTTP_PORT = 8088
HTTPS_PORT = 8443
HOSTNAME = 'bm.weotzi.com'
TZ = 'America/Argentina/Buenos_Aires'
IPV4_NETWORK = '172.66.1'  # verified safe (no collision with existing networks)


def randpass(n=32, alphabet=None):
    if alphabet is None:
        # Avoid characters that confuse shell/env files: $, `, \, ", ', =, /, :
        alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(n))


def randhex(n=24):
    return secrets.token_hex(n)


def build_env(existing_env=None):
    """Return the full content of /opt/billionmail/.env. Reuse credentials if a previous
    .env already exists so re-running the script doesn't rotate secrets."""
    e = existing_env or {}
    return {
        'ADMIN_USERNAME': e.get('ADMIN_USERNAME') or 'weotzi_admin',
        'ADMIN_PASSWORD': e.get('ADMIN_PASSWORD') or randpass(28),
        'SafePath': e.get('SafePath') or randpass(20, string.ascii_lowercase + string.digits),
        'BILLIONMAIL_HOSTNAME': HOSTNAME,
        'DBNAME': e.get('DBNAME') or 'billionmail',
        'DBUSER': e.get('DBUSER') or 'billionmail',
        'DBPASS': e.get('DBPASS') or randhex(24),
        'REDISPASS': e.get('REDISPASS') or randhex(24),
        'SMTP_PORT': '25',
        'SMTPS_PORT': '465',
        'SUBMISSION_PORT': '587',
        'IMAP_PORT': '143',
        'IMAPS_PORT': '993',
        'POP_PORT': '110',
        'POPS_PORT': '995',
        'REDIS_PORT': '127.0.0.1:26379',
        'SQL_PORT': '127.0.0.1:25432',
        'HTTP_PORT': str(HTTP_PORT),
        'HTTPS_PORT': str(HTTPS_PORT),
        'TZ': TZ,
        'IPV4_NETWORK': IPV4_NETWORK,
        'FAIL2BAN_INIT': 'y',
        'IP_WHITELIST_ENABLE': 'false',
        'RETENTION_DAYS': '7',
    }


def parse_env_file(content):
    out = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            k, v = line.split('=', 1)
            out[k.strip()] = v.strip()
    return out


def render_env(env):
    lines = [
        '# Generated by scripts/billionmail/install_billionmail.py',
        '# DO NOT commit this file. It contains secrets.',
        '',
        f'ADMIN_USERNAME={env["ADMIN_USERNAME"]}',
        f'ADMIN_PASSWORD={env["ADMIN_PASSWORD"]}',
        f'SafePath={env["SafePath"]}',
        '',
        f'BILLIONMAIL_HOSTNAME={env["BILLIONMAIL_HOSTNAME"]}',
        '',
        f'DBNAME={env["DBNAME"]}',
        f'DBUSER={env["DBUSER"]}',
        f'DBPASS={env["DBPASS"]}',
        '',
        f'REDISPASS={env["REDISPASS"]}',
        '',
        '## MAIL Ports',
        f'SMTP_PORT={env["SMTP_PORT"]}',
        f'SMTPS_PORT={env["SMTPS_PORT"]}',
        f'SUBMISSION_PORT={env["SUBMISSION_PORT"]}',
        f'IMAP_PORT={env["IMAP_PORT"]}',
        f'IMAPS_PORT={env["IMAPS_PORT"]}',
        f'POP_PORT={env["POP_PORT"]}',
        f'POPS_PORT={env["POPS_PORT"]}',
        f'REDIS_PORT={env["REDIS_PORT"]}',
        f'SQL_PORT={env["SQL_PORT"]}',
        '',
        '## Manage Ports (custom: avoid Traefik on 80/443)',
        f'HTTP_PORT={env["HTTP_PORT"]}',
        f'HTTPS_PORT={env["HTTPS_PORT"]}',
        '',
        f'TZ={env["TZ"]}',
        f'IPV4_NETWORK={env["IPV4_NETWORK"]}',
        f'FAIL2BAN_INIT={env["FAIL2BAN_INIT"]}',
        f'IP_WHITELIST_ENABLE={env["IP_WHITELIST_ENABLE"]}',
        f'RETENTION_DAYS={env["RETENTION_DAYS"]}',
        '',
    ]
    return '\n'.join(lines)


def step(msg):
    print(f'\n=== {msg} ===')


def main():
    ssh, creds = connect()
    print(f'Connected to {creds["BM_HOST"]} as {creds["BM_USER"]}.')

    step('1. Verify Docker and Compose')
    out, _, _ = run(ssh, 'docker --version && docker compose version', check=True)
    print(out)

    step('2. Ensure repo at ' + REPO_DIR)
    out, _, code = run(ssh, f'test -d {REPO_DIR}/.git')
    if code == 0:
        print(f'{REPO_DIR} already a git repo. Pulling latest...')
        run(ssh, f'cd {REPO_DIR} && git pull --ff-only', check=True)
    else:
        out, _, _ = run(ssh, f'test -d {REPO_DIR} && ls -la {REPO_DIR} | head')
        if out:
            print(f'{REPO_DIR} exists but not a git repo. Backing up...')
            ts = time.strftime('%Y%m%d_%H%M%S')
            run(ssh, f'mv {REPO_DIR} {REPO_DIR}.bak.{ts}', check=True)
        print('Cloning BillionMail...')
        run(
            ssh,
            f'git clone --depth 1 {REPO_URL} {REPO_DIR}',
            check=True,
            timeout=180,
        )
    out, _, _ = run(ssh, f'cd {REPO_DIR} && git rev-parse HEAD && git rev-parse --abbrev-ref HEAD')
    print('Repo HEAD:\n' + out)

    step('3. Build / preserve .env')
    out, _, code = run(ssh, f'cat {REPO_DIR}/.env 2>/dev/null')
    if code == 0 and out:
        existing = parse_env_file(out)
        print('.env already exists, preserving secrets and updating non-secret fields.')
    else:
        existing = {}
        print('.env does not exist, generating fresh secrets.')

    env = build_env(existing)
    env_text = render_env(env)
    write_remote_file(ssh, f'{REPO_DIR}/.env', env_text)
    run(ssh, f'chmod 600 {REPO_DIR}/.env', check=True)
    print(f'Wrote {REPO_DIR}/.env (chmod 600).')
    print()
    print(f'  Admin user      : {env["ADMIN_USERNAME"]}')
    print(f'  Admin password  : {env["ADMIN_PASSWORD"]}')
    print(f'  SafePath        : /{env["SafePath"]}')
    print(f'  Hostname        : {env["BILLIONMAIL_HOSTNAME"]}')
    print(f'  HTTP / HTTPS    : {env["HTTP_PORT"]} / {env["HTTPS_PORT"]}  (proxy via Traefik)')
    print('  Save these credentials securely.')

    step('4. docker compose pull (download images)')
    out, _, _ = run(
        ssh, f'cd {REPO_DIR} && docker compose pull 2>&1 | tail -40', timeout=600
    )
    print(out)

    step('5. docker compose up -d')
    out, _, code = run(
        ssh, f'cd {REPO_DIR} && docker compose up -d 2>&1', timeout=600
    )
    print(out)
    if code != 0:
        print('docker compose up FAILED with exit code', code)
        ssh.close()
        sys.exit(1)

    step('6. Wait 20s and check container health')
    time.sleep(20)
    out, _, _ = run(
        ssh,
        'docker ps --filter "name=billionmail" --format "table {{.Names}}\\t{{.Status}}\\t{{.Ports}}"',
    )
    print(out)

    step('7. Local health check (panel)')
    out, _, _ = run(
        ssh, f'curl -ks -o /dev/null -w "%{{http_code}}" https://127.0.0.1:{HTTPS_PORT}/'
    )
    print(f'panel https://127.0.0.1:{HTTPS_PORT} -> HTTP {out}')
    out, _, _ = run(
        ssh, f'curl -s -o /dev/null -w "%{{http_code}}" http://127.0.0.1:{HTTP_PORT}/'
    )
    print(f'panel http://127.0.0.1:{HTTP_PORT}  -> HTTP {out}')

    step('Done')
    print(f'BillionMail is running. Access:')
    print(f'  Panel (LAN, self-signed): https://127.0.0.1:{HTTPS_PORT}/{env["SafePath"]}/')
    print('Next steps:')
    print('  1. Add DNS records for mail.weotzi.com (A record -> 69.62.98.207).')
    print('  2. Configure Traefik in Easypanel to proxy mail.weotzi.com -> 127.0.0.1:%d' % HTTP_PORT)
    print('  3. Login to the panel, generate API key, run scripts/billionmail/get_dns_records.py.')

    ssh.close()


if __name__ == '__main__':
    main()
