"""
Read /opt/billionmail/.env from the VPS and write a local copy of the panel
credentials to .billionmail-panel-credentials (gitignored).

This file is for the developer's reference (admin login, DB pass, redis pass, etc.).
The API key still has to be generated from the BillionMail panel after first login.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from _ssh import connect, run  # type: ignore

OUT = os.path.join(
    os.path.dirname(__file__), '..', '..', '.billionmail-panel-credentials'
)


def main():
    ssh, _ = connect()
    out, _, _ = run(ssh, 'cat /opt/billionmail/.env')
    ssh.close()

    if not out:
        print('Could not read .env')
        sys.exit(1)

    keys = [
        'ADMIN_USERNAME', 'ADMIN_PASSWORD', 'SafePath',
        'BILLIONMAIL_HOSTNAME', 'HTTP_PORT', 'HTTPS_PORT',
        'DBNAME', 'DBUSER', 'DBPASS', 'REDISPASS',
    ]
    parsed = {}
    for line in out.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        parsed[k.strip()] = v.strip()

    safepath = parsed.get('SafePath', '')
    hostname = parsed.get('BILLIONMAIL_HOSTNAME', '')

    content = [
        '# BillionMail panel credentials (gitignored).',
        '# Generated by scripts/billionmail/save_panel_credentials.py',
        '#',
        '# Once DNS A record bm.weotzi.com -> 69.62.98.207 propagates,',
        f'# panel will be available at https://{hostname}/{safepath}/',
        '#',
        '# To access the panel right now (before DNS), open an SSH tunnel:',
        '#   ssh -L 8443:127.0.0.1:8443 root@69.62.98.207',
        f'#   then browse: https://localhost:8443/{safepath}/',
        '#',
        '# Generate an API key from Settings -> API and add it as BILLIONMAIL_API_KEY',
        '# in .env (or paste it here for safekeeping).',
        '',
    ]
    for k in keys:
        if k in parsed:
            content.append(f'{k}={parsed[k]}')

    content.append('')
    content.append('# === Filled in after first login ===')
    content.append('BILLIONMAIL_API_KEY=')
    content.append(f'BILLIONMAIL_API_URL=https://{hostname}')
    content.append('BILLIONMAIL_DEFAULT_SENDER=noreply@weotzi.com')
    content.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(content))

    print(f'Wrote {OUT}')
    print(f'Admin user: {parsed.get("ADMIN_USERNAME")}')
    print(f'Admin pass: {parsed.get("ADMIN_PASSWORD")}')
    print(f'SafePath:   /{parsed.get("SafePath")}/')
    print(f'Panel URL:  https://{hostname}/{parsed.get("SafePath")}/  (after DNS)')


if __name__ == '__main__':
    main()
