-- Only the server may persist web intake. It derives the opaque quote ID
-- from a browser-held random key; that key is never stored in the public row.
create or replace function public.save_web_quotation(p_quote jsonb,p_extras jsonb)
returns jsonb language plpgsql set search_path=public,pg_temp as $$
declare q public.quotations_db; saved public.quotations_db;
begin
  q := jsonb_populate_record(null::public.quotations_db,p_quote);
  if q.quote_id !~ '^QN[0-9a-f]{32}$' or q.quote_status not in ('in_progress','pending') then raise exception 'Invalid web intake'; end if;
  insert into public.quotations_db (tattoo_body_part,tattoo_body_side,tattoo_idea_description,tattoo_size,tattoo_style,tattoo_color_type,reference_images_count,tattoo_references,tattoo_is_first_tattoo,tattoo_is_cover_up,client_full_name,client_email,client_instagram,client_city_residence,client_travel_willing,city_mismatch_acknowledged,style_mismatch_acknowledged,client_preferred_date,client_flexible_dates,client_budget_amount,client_budget_currency,client_contact_preference,client_whatsapp,client_birth_date,client_age,client_health_conditions,client_allergies,tattoo_estimated_sessions,quote_id,quote_status,client_user_id,artist_id,artist_name,artist_email,artist_instagram,artist_styles,artist_current_city,artist_studio_name,artist_session_cost_amount,quotation_medium,source)
  values (q.tattoo_body_part,q.tattoo_body_side,q.tattoo_idea_description,q.tattoo_size,q.tattoo_style,q.tattoo_color_type,q.reference_images_count,q.tattoo_references,q.tattoo_is_first_tattoo,q.tattoo_is_cover_up,q.client_full_name,q.client_email,q.client_instagram,q.client_city_residence,q.client_travel_willing,q.city_mismatch_acknowledged,q.style_mismatch_acknowledged,q.client_preferred_date,q.client_flexible_dates,q.client_budget_amount,q.client_budget_currency,q.client_contact_preference,q.client_whatsapp,q.client_birth_date,q.client_age,q.client_health_conditions,q.client_allergies,q.tattoo_estimated_sessions,q.quote_id,q.quote_status,q.client_user_id,q.artist_id,q.artist_name,q.artist_email,q.artist_instagram,q.artist_styles,q.artist_current_city,q.artist_studio_name,q.artist_session_cost_amount,q.quotation_medium,q.source)
  on conflict (quote_id) do update set tattoo_body_part=excluded.tattoo_body_part,tattoo_body_side=excluded.tattoo_body_side,tattoo_idea_description=excluded.tattoo_idea_description,tattoo_size=excluded.tattoo_size,tattoo_style=excluded.tattoo_style,tattoo_color_type=excluded.tattoo_color_type,reference_images_count=excluded.reference_images_count,tattoo_references=excluded.tattoo_references,tattoo_is_first_tattoo=excluded.tattoo_is_first_tattoo,tattoo_is_cover_up=excluded.tattoo_is_cover_up,client_full_name=excluded.client_full_name,client_email=excluded.client_email,client_instagram=excluded.client_instagram,client_city_residence=excluded.client_city_residence,client_travel_willing=excluded.client_travel_willing,city_mismatch_acknowledged=excluded.city_mismatch_acknowledged,style_mismatch_acknowledged=excluded.style_mismatch_acknowledged,client_preferred_date=excluded.client_preferred_date,client_flexible_dates=excluded.client_flexible_dates,client_budget_amount=excluded.client_budget_amount,client_budget_currency=excluded.client_budget_currency,client_contact_preference=excluded.client_contact_preference,client_whatsapp=excluded.client_whatsapp,client_birth_date=excluded.client_birth_date,client_age=excluded.client_age,client_health_conditions=excluded.client_health_conditions,client_allergies=excluded.client_allergies,tattoo_estimated_sessions=excluded.tattoo_estimated_sessions,quote_status=excluded.quote_status,client_user_id=excluded.client_user_id,artist_id=excluded.artist_id,artist_name=excluded.artist_name,artist_email=excluded.artist_email,artist_instagram=excluded.artist_instagram,artist_styles=excluded.artist_styles,artist_current_city=excluded.artist_current_city,artist_studio_name=excluded.artist_studio_name,artist_session_cost_amount=excluded.artist_session_cost_amount,quotation_medium=excluded.quotation_medium,source=excluded.source,updated_at=now()
  where quotations_db.quote_status='in_progress'
  returning * into saved;
  if saved.id is null then
    select * into saved from public.quotations_db where quote_id=q.quote_id;
  else
    insert into public.quotation_intake_extras(quote_id,idea_mode,personalization_level,reference_notes)
    values(saved.quote_id,p_extras->>'idea_mode',p_extras->>'personalization_level',coalesce(p_extras->'reference_notes','[]'::jsonb))
    on conflict(quote_id) do update set idea_mode=excluded.idea_mode,personalization_level=excluded.personalization_level,reference_notes=excluded.reference_notes;
  end if;
  return jsonb_build_object('quote_id',saved.quote_id,'status',saved.quote_status);
end; $$;
revoke all on function public.save_web_quotation(jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.save_web_quotation(jsonb,jsonb) to service_role;
